In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## define size
voc_size=10000

In [16]:
## one hot representation
one_hot_repr=[one_hot(word,voc_size)for word in sent] 

In [17]:
one_hot_repr

[[5235, 6695, 3455, 2240],
 [5235, 6695, 3455, 9289],
 [5235, 7430, 3455, 4208],
 [9749, 1011, 6091, 8153, 2696],
 [9749, 1011, 6091, 8153, 2135],
 [220, 5235, 9570, 3455, 2582],
 [9214, 5482, 4902, 8153]]

In [19]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [20]:
import numpy as np

In [25]:
sen_len=8
embaded = pad_sequences(one_hot_repr,padding='pre',maxlen=sen_len)

In [ ]:
print(embaded)

[[   0    0    0    0 5235 6695 3455 2240]
 [   0    0    0    0 5235 6695 3455 9289]
 [   0    0    0    0 5235 7430 3455 4208]
 [   0    0    0 9749 1011 6091 8153 2696]
 [   0    0    0 9749 1011 6091 8153 2135]
 [   0    0    0  220 5235 9570 3455 2582]
 [   0    0    0    0 9214 5482 4902 8153]]


In [27]:
## feature representation
dim=10

In [28]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sen_len))
model.compile('adam','mse')
## adam is optimizer

In [29]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [30]:
model.predict(embaded)

1/1 [==============================] - 0s 366ms/step


array([[[ 2.96902396e-02,  4.83078025e-02,  3.63825075e-02,
         -4.07056324e-02, -4.18003649e-03,  2.51369961e-02,
         -2.22437382e-02,  2.28607766e-02, -2.19822880e-02,
          3.16305272e-02],
        [ 2.96902396e-02,  4.83078025e-02,  3.63825075e-02,
         -4.07056324e-02, -4.18003649e-03,  2.51369961e-02,
         -2.22437382e-02,  2.28607766e-02, -2.19822880e-02,
          3.16305272e-02],
        [ 2.96902396e-02,  4.83078025e-02,  3.63825075e-02,
         -4.07056324e-02, -4.18003649e-03,  2.51369961e-02,
         -2.22437382e-02,  2.28607766e-02, -2.19822880e-02,
          3.16305272e-02],
        [ 2.96902396e-02,  4.83078025e-02,  3.63825075e-02,
         -4.07056324e-02, -4.18003649e-03,  2.51369961e-02,
         -2.22437382e-02,  2.28607766e-02, -2.19822880e-02,
          3.16305272e-02],
        [-6.40384108e-03, -2.93162707e-02,  2.62098424e-02,
          4.09716703e-02, -4.78283316e-03,  3.63747738e-02,
          1.63721107e-02,  3.92652266e-02, -2.414339